version: '3.9'

services:
   web:
       build: .
       command: gunicorn config.wsgi:application --bind 0.0.0.0:80
       expose:
         - "80"
       volumes:
         - media_volume:/app/media
         - static_volume:/app/static
       env_file:
         - ./config/.env
       depends_on:
         - postgres

   postgres:
     image: postgres:16.1-alpine3.19
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     environment:
       - POSTGRES_USER=Alkanoid
       - POSTGRES_PASSWORD=jh5|22Kz_nC@
       - POSTGRES_DB=reformator

   nginx:
     image: nginx:1.25.3-alpine
     hostname: reformator
     ports:
       - "80:80"
     volumes:
       - media_volume:/app/media
       - static_volume:/app/static
       - ./var/log/nginx:/var/log/nginx
       - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./volumes/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
       - ./volumes/etc/nginx/ssl:/etc/nginx/ssl
       - /var/www/DOMAIN_NAME:/var/www/DOMAIN_NAME
     depends_on:
       - web

volumes:
  postgres_data:
  media_volume:
  static_volume:
